from tortoise import BaseDBAsyncClient

RUN_IN_TRANSACTION = True


async def upgrade(db: BaseDBAsyncClient) -> str:
    return """
        CREATE TABLE IF NOT EXISTS "games" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "min_players" INT NOT NULL DEFAULT 2,
    "max_players" INT NOT NULL DEFAULT 4,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "players" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "game_sessions" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "played_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "notes" TEXT,
    "game_id" INT NOT NULL REFERENCES "games" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "scores" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "points" INT,
    "winner" INT NOT NULL DEFAULT 0,
    "player_id" INT NOT NULL REFERENCES "players" ("id") ON DELETE CASCADE,
    "session_id" INT NOT NULL REFERENCES "game_sessions" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "aerich" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "version" VARCHAR(255) NOT NULL,
    "app" VARCHAR(100) NOT NULL,
    "content" JSON NOT NULL
);"""


async def downgrade(db: BaseDBAsyncClient) -> str:
    return """
        """


MODELS_STATE = (
    "eJztmWFT2jAYx79Kr6/wju2EiXq8A0RlKnjCNs/drhfaWHKmCSZhyjm++y5pS9pQGDhEOP"
    "uK8iRPk/ySPM+/yYsdUA9i/vkMBNCuWi82CR9S9qJlg+FQW6VBgD5WFX0QQGUBfS4YcIVd"
    "te4B5rBo2R7kLkNDgSixqxYZYSyN1OWCIeJr04igxxF0BPWhGEBmV62fv4qWjYgHnyGP/w"
    "4fnHsEsZfqJ/Jk28ruiPFQ2VpEnKqKsrW+41I8CoiuPByLASXT2ogIafUhgQwIKF8v2Eh2"
    "X/YuGmY8orCnukrYxYSPB+/BCIvEcJdk4FIi+SEi5IBfbF+28qlcOjg6OP5yeHBctGzVk6"
    "nlaBIOT489dFQE2j17osqBAGENhVFzU78z5BoDwLLRxfUNeFwwE16MahG92KDx6SWzJn4B"
    "eHYwJL4YSGiVygJa32s3jfPaTaFcqezJ0VAG3HBxt6OiclgmkSa2CCLOEIMxZHyFNWh4/X"
    "sxrotn+b0XY4IceH4NubTX5sgdbA85l0E5OAeIWXAnQECBAphNL+1pwPMi18/xw5ZuagaB"
    "1yF4HMXbBeh6ratmt1e7upYjCTh/xApRrdeUJWVlHRvWwqGx/acvsX60eueW/GvdddpNRZ"
    "By4TPVoq7Xu7Nln8BIUIfQJwd4idQQW2MwE5nU7qOkNs1yfeA+PAHmOakSvQI45BxRkrFx"
    "6pHn6cUNxECxnZ3pRF7vhm/azqmOplZb4ymXjGiZzqM2WxSUA9MCCPBVr2XbsqWIyrWKLl"
    "k6KCpZqIQSsSnXQrkW+lBaKM9LHz4vuVS2+l9ZqSvfsZ1T/C75KJml53ycJ5L44m90Jykc"
    "8vy0S/lJCYvXxNaUYx5atyC0JnMmoSIrYPbg85wtMXV4lfCIurT5mJk5V83bXmqaYnVRuK"
    "rd7qWm6rLTPourJ9RI47JTN0SICnMrBZmEx+aOE94/2Mwk+DTDWYCnlEHkkws4VhxbhAtA"
    "3CwRbJwb704iL1o2A0/TrJVcGpQ4HsRQhJ8FtW6jdtK0FcRcFG1eFIU8MuTQFNR8IaTnI1"
    "dAO6WAqGppeXba4VVxffO5ct0HxU+IkPDAyog8lGIISDY17WRQ61OK3yoErbr9lhcZ9U7n"
    "MiUy6i1TRXy7qjdvCiWlOPgjRmGMn8UZnu2tJi5SPh9JXiTBRV+dq5FLO30kdAuUWQRlTe"
    "JsJw//TY2WXifZMm12F6+BoL4O2F14qfC0qsR9S4FXgwy5gyyFF5UslHhA18kl3g5JvN+Q"
    "ZYe3+fcwCZf8KmYKUm6NFSBG1XcTYGl/fwmApf39uQBVmXGXRYmA4R5MQ/za7bTnXGJpF/"
    "OYFbnC+mNhxLdUtUzm85PjXXxIZ57HGYek8gXykG6FC6X1J5bJX5v9Ht0="
)
